FROM python:3.11.3
WORKDIR C:\Users\josaf\Documents\ProyectoCoder
COPY requirements.txt .
COPY APi.py .
COPY Entregable2.py .
COPY main.py .
RUN pip install -r requirements.txt
CMD ["python","APi.py","Entregable2.py","main.py"]



